import streamlit as st
import os
import time
from dotenv import load_dotenv

# Import your agents
from agents.logic.planner_agent import PlannerAgent
from agents.logic.search_agent import SearchAgent
from agents.logic.analysis_agent import AnalysisAgent
from agents.logic.hypothesis_agent import HypothesisAgent
from agents.logic.synthesis_agent import SynthesisAgent

# Load environment variables
load_dotenv()

# Page Config
st.set_page_config(page_title="ResearchPilot AI", page_icon="🚀", layout="wide")

# Custom Styling
st.markdown("""
    <style>
    .main { background-color: #0e1117; color: white; }
    .stButton>button { width: 100%; border-radius: 5px; height: 3em; background-color: #FF4B4B; color: white; }
    </style>
    """, unsafe_allow_html=True)

def main():
    st.title("🚀 ResearchPilot AI")
    st.subheader("Your Agentic Scientific Collaborator")
    
    # Sidebar for Model & API Info
    with st.sidebar:
        st.header("⚙️ System Configuration")
        st.info("Model: Llama 3.3 70B (Groq)")
        st.success("Web Search: Tavily AI Enabled")
        st.divider()
        st.markdown("### Agent Team Status")
        st.write("✅ Planner | ✅ Researcher | ✅ Analyst | ✅ Hypothesizer")

    # User Input Area
    query = st.text_area("Enter your research topic:", placeholder="e.g., The long-term impact of Agentic AI on Bangalore's startup ecosystem...")
    
    if st.button("Start Research Mission"):
        if not query.strip():
            st.warning("Please enter a valid research topic.")
            return

        # Initialize Agents
        planner = PlannerAgent()
        searcher = SearchAgent()
        analyzer = AnalysisAgent()
        hypothesizer = HypothesisAgent()
        synthesizer = SynthesisAgent()

        # Step-by-step Execution with Status Container
        with st.status("🤖 AI Agents are collaborating...", expanded=True) as status:
            
            # 1. Planning
            st.write("📋 **PlannerAgent**: Breaking down the mission into sub-tasks...")
            plan = planner.generate_plan(query)
            st.write(f"Objective established: {len(plan)} focus areas identified.")
            
            results_pool = []
            
            # 2. Sequential Search & Analysis
            for i, sub_query in enumerate(plan):
                st.write(f"🔍 **SearchAgent**: Investigating '{sub_query}'...")
                raw_data = searcher.execute_search(sub_query)
                
                st.write(f"🧠 **AnalysisAgent**: Synthesizing data for phase {i+1}...")
                analysis = analyzer.analyze_results(sub_query, raw_data)
                results_pool.append(analysis)
                
            # 3. Hypothesis Generation
            st.write("🧪 **HypothesisAgent**: Ideating novel scientific propositions...")
            combined_analysis = "\n\n".join(results_pool)
            hypotheses = hypothesizer.generate_hypotheses(query, combined_analysis)
            
            # 4. Final Synthesis
            st.write("✍️ **SynthesisAgent**: Polishing the final comprehensive report...")
            final_report = synthesizer.synthesize(query, results_pool + [hypotheses])
            
            status.update(label="Mission Accomplished!", state="complete", expanded=False)

        # Tabs for Output
        tab1, tab2 = st.tabs(["📄 Final Report", "🧪 Hypothesis Lab"])
        
        with tab1:
            st.markdown(final_report)
            st.download_button(
                label="📥 Download Full Report (MD)",
                data=final_report,
                file_name=f"Research_Report_{int(time.time())}.md",
                mime="text/markdown"
            )
            
        with tab2:
            st.header("Novel Hypotheses")
            st.info("These are testable predictions generated by the AI based on current data gaps.")
            st.markdown(hypotheses)

if __name__ == "__main__":
    main()